### PR TITLE
(Feature) Allow cancellation of a ballot in `VotingToManageEmissionFunds` by its creator for 15 minutes after it's created

### PR DESCRIPTION
**Pull request by varasev**
- (Mandatory) Description
Solves the issue https://github.com/poanetwork/poa-network-consensus-contracts/issues/161.

- (Mandatory) What is it: (Fix), (Feature), or (Refactor)
(Feature)

### CODE REVIEW

**Comment by wkarshat** [comment]
@varasev, perhaps this is the logic you are looking for in _finalize() of VotingToManageEmissionFunds.sol

```
    uint256 sendVotesCount = _getSendVotes(_id);
    uint256 burnVotesCount = _getBurnVotes(_id);
    uint256 freezeVotesCount = _getFreezeVotes(_id);
    QuorumStates quorumState = QuorumStates.Frozen;
        
    if (sendVotesCount > burnVotesCount)
    {
        if (sendVotesCount > freezeVotesCount)
            quorumState = QuorumStates.Sent;
    } else {
        if (burnVotesCount > sendVotesCount && burnVotesCount > freezeVotesCount)
            quorumState = QuorumStates.Burnt;
    }

```

However, is that desirable, could say Burn pass with 4:3:3 against Sent and Frozen?

**Comment by varasev** [comment]
@wkarshat Yes, that's a very good simplification, thank you! I merged your code in https://github.com/poanetwork/poa-network-consensus-contracts/pull/181.

**Comment by wkarshat** [comment]
Sure.

What's the expected value, i.e. on Sokol, of:
        uint256 validatorsLength = IPoaNetworkConsensus()

Can you help with understand how the section starting line 189 works?
        releaseTime = releaseTime.add(releaseThreshold.mul(diff));
I would think you'd increment from CurrentTime and not releaseTime.

**Comment by varasev** [comment]
> What's the expected value, i.e. on Sokol, of: uint256 validatorsLength = 

There are `25` validators in `Sokol` for now (including MoC), so `validatorsLength` will be `24` (excluding MoC), because MoC has no voting rights.

> Can you help with understand how the section starting line 189 works?

I'll try to explain it on the picture:

image

So, we have different timestamps called `releaseTime` on the timeline. They are separated by `emissionReleaseThreshold` which is 3 months (as described in https://github.com/poanetwork/RFC/issues/14#issuecomment-386990302).

Let's assume that the `currentTime` is `4 July` and the current `emissionReleaseTime` in the smart contract is `1 January`. E.g., we didn't create any ballot since `1 January`, so `emissionReleaseTime` was not refreshed so far.

So, now is `4 July` and we want to create a new ballot. We should refresh `emissionReleaseTime` and shift it to `1 July`. When we call `createBallot` function, it will call `refreshEmissionReleaseTime` automatically.

According to

```
uint256 diff = currentTime.sub(releaseTime).div(releaseThreshold);
```

we have

`diff` = (`4 July` - `1 January`) / `3 months` = 2

Therefore

```
releaseTime = releaseTime.add(releaseThreshold.mul(diff));
```

will give us

`releaseTime` = `1 January` + (`3 months` * 2)

i.e.

`releaseTime` = `1 January` + `6 months` = `1 July`

**Comment by varasev** [comment]
> Starting on Oct 1st and for seven days thereafter, one of the Validators can introduce this type of a vote, and for 15 minutes after can cancel. Somehow, once this vote has been introduced (and not cancelled) no other Validator can introduce one of this type. Presumably, once cancelled it can be re-introduced. Presumably, once passed, this type of a vote cannot be re-introduced.

That's right. Once passed, this type of a vote cannot be re-introduced until the next `releaseTime` timestamp (in 3 months after Oct 1st) and unless the previous ballot is finalized.

> The minimum number of votes necessary to pass is 4 (quorum)

No, for the current set of validators in Sokol (24 persons excluding MoC) the minimum number will be `24 / 2 + 1 = 13`.

That's defined here: https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/VotingToManageEmissionFunds.sol#L293-L295

> Voting has to complete within 7 days (after Oct 1st).

Yes, 7 days is the maximum period of time when validators can give their votes, so called `distribution threshold`, as described in https://github.com/poanetwork/RFC/issues/14#issuecomment-386990302

> BTW, what are the options for the duration, fixed or set by the Validator, within the limits of other vote types, like 48 hours?

We have no minimum limit of duration of this type of a ballot assuming that the `startTime` and `endTime` timestamps will be calculated automatically and defined by Governance DApp when creating a new ballot. Also, validators might late and create a ballot, for example, on Oct 5th evening, when there are less than 48 hours left to the end of distribution threshold (Oct 7th). However, we could introduce such a minimum limit for this type of a ballot in `VotingToManageEmissionFunds` smart contract if necessary.

> The default behavior is Hold, in cases that the Burn or Payout did not win or quorum not achieved or time expired. BTW, I'm not sure I saw a test case for the last one.

Yes, if time expired and quorum (or majority) not achieved, the `finalize` function will set `frozen` state: https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/VotingToManageEmissionFunds.sol#L238 and https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/VotingToManageEmissionFunds.sol#L258

E.g., we have the next unit tests for those cases: https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/test/voting_to_manage_emission_funds_test.js#L754-L812

> In order to pass, Burn or Payout need most votes (more than either one of the other two options, no tie). So, in case of Burn:Pay:Hold votes of 7:6:5, Burn would pass.

Yes, right. A few cases for example:

```
Burn = 7 (pass, because greater than Pay or Hold)
Pay = 6
Hold = 5

Burn = 6
Pay = 6
Hold = 5 (pass, because of tie for Burn and Pay)

Burn = 6 (pass, because greater than Pay or Hold)
Pay = 5
Hold = 5

Burn = 5
Pay = 6 (pass, because greater than Burn or Hold)
Hold = 5

Burn = 4
Pay = 6 (pass, because greater than Burn or Hold)
Hold = 5

etc.
```

**Comment by wkarshat** [comment]
At which point does the check for 13 votes kick in, please?

**Comment by varasev** [comment]
It happens on the next line: https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/VotingToManageEmissionFunds.sol#L237

When we call `createBallot` function, it calls `VotingTo._createBallot`: https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/VotingToManageEmissionFunds.sol#L86

which sets `MinThresholdOfVoters` here:

https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/abstracts/VotingTo.sol#L149

It calls `VotingToManageEmissionFunds._getGlobalMinThresholdOfVoters` function which overrides `VotingTo._getGlobalMinThresholdOfVoters`.

The code of `VotingToManageEmissionFunds._getGlobalMinThresholdOfVoters` is:

https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/VotingToManageEmissionFunds.sol#L293-L295

I.e., it calls BallotsStorage.getProxyThreshold():

https://github.com/poanetwork/poa-network-consensus-contracts/blob/6c2c7798394ed14abcfb53fe9ce6269cd83630ff/contracts/BallotsStorage.sol#L131-L133

**Comment by wkarshat** [comment]
@varasev, thanks hugely for the details.  I'm impressed by how the system of smart contracts is layered and hangs together.
So, my understanding is that the smallest number of votes that can win is 5, if the votes are 5:4:4, for a total of 13.

**Comment by varasev** [comment]
@wkarshat

> thanks hugely for the details. I'm impressed by how the system of smart contracts is layered and hangs together.

Thank you.

> So, my understanding is that the smallest number of votes that can win is 5, if the votes are 5:4:4, for a total of 13.

Yes, right.

**Comment by shkron** [comment]
@varasev, do I understand this correctly, in the scenario like this:
> Burn = 12
> Pay = 12
> Hold = 0 (pass, because of tie for Burn and Pay)

Also could you please provide the definitions for those options.

**Comment by 6proof** [comment]
I think most Validators would expect minimum voting period to be 48 hours (as is case for other ballots).  This would seem to be a minimum floor, particularly for subject of this type of ballot, and would hope this minimum would be added.

**Comment by varasev** [comment]
@shkron

> do I understand this correctly, in the scenario like this:
> Burn = 12
> Pay = 12
> Hold = 0 (pass, because of tie for Burn and Pay)

Yes, you do, because there is no majority of votes: `Burn = Pay`, so we can't make a concrete decision.

> also what happens in this case?
> Burn = 0
> Pay = 12
> Hold = 12

In this case `Hold` wins for the same reason as above. `Hold` always wins in case of no majority.

> Also could you please provide the definitions for those options.

You can see conditions here: https://github.com/poanetwork/poa-network-consensus-contracts/blob/8acbbe11cec80c1462b5291f8b09f3ee40d319a1/contracts/VotingToManageEmissionFunds.sol#L237-L256

**Comment by varasev** [comment]
@6proof ok, the corresponding issue has been opened: https://github.com/poanetwork/poa-network-consensus-contracts/issues/190.

**Comment by vbaranov** [comment]
@varasev maybe, we could create a page in Governance section of [wiki repo](https://github.com/poanetwork/wiki), that describes every threshold and the process overall? I assume it will be more transparent for everyone.

**Comment by varasev** [comment]
@vbaranov Sure, I'll create one.

**Review by alfredomontes37826-ux — APPROVED** [review]

**Pull request merged**
